version: "3"
services:
  service.vcfannotation.unite:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: unite.vcfannotation.service
    container_name: unite.vcfannotation.service
    environment:
      PYTHONPATH: "/usr/local/lib/python3.6/dist-packages/:/usr/local/lib/python3.6/dist-packages/UNITEmsc-0.0.1-py3.6.egg/UNITEmsc:/usr/local/lib/python3.6/dist-packages/UNITEannotatevcf-0.0.9-py3.6.egg/UNITEvcfannotation"
    volumes:
      - ${HOST_ANNOTATIONS_TOOL_DIR}:/opt/vep/.vep
      - ${HOST_FILE_DIR}:/mnt/filestobeparsed      
    ports:
      - 127.0.0.1:5201:5201
    cap_add:
      - SYS_ADMIN
    security_opt:
      - "apparmor:unconfined"
networks:
  default:
    external:
      name: unite
